# Generated by Django 3.0.5 on 2020-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
