# Generated by Django 3.0.5 on 2020-04-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_rest', '0002_auto_20200407_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
