# Generated by Django 3.0.5 on 2020-04-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_rest', '0003_remove_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
